//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "category_specs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub category_id: Uuid,
    pub spec_name: String,
    pub spec_type: String,
    pub is_required: Option<bool>,
    pub preset_options: Option<Json>,
    pub validation_rules: Option<Json>,
    pub input_placeholder: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub helper_text: Option<String>,
    pub sort_order: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Categories,
    #[sea_orm(has_many = "super::product_specs::Entity")]
    ProductSpecs,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::product_specs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductSpecs.def()
    }
}
